// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Session struct {
	ID        string
	ExpiresAt time.Time
	UserID    string
}

type User struct {
	ID        string
	CreatedAt time.Time
	Name      string
	Email     string
	Password  string
}
