// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, expires_at, user_id)
VALUES($1, $2, $3)
RETURNING id
`

type CreateSessionParams struct {
	ID        string
	ExpiresAt time.Time
	UserID    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.ExpiresAt, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}
